### ISSUE TITLE
[Suggestion] Make Cool Picker

### ISSUE THREAD

**Issue by sololance** [kevinfaguiar/cool-emoji-picker#1]
Hi!

Nice plugin, well done.

There is a big space for good emoji picker written for vuejs without performance problems. The only problem with cooltextarea is hard to integrate on already having text area as component.

So my question is: will you divide _cooltexarea_ to _coolpicker_ maybe 👍 ?

Thank you.

**Comment by kevinfaguiar** [comment]
At the moment I am considering the possibilities, which are two. As you suggested maybe create another project only with the Emoji Picker.

The problem with this approach is if you want to render the emoji from the Twemoji library you will need to develop your own "content-editable" web component, which gives some work considering COPY / PASTE etc.

As it stands today anyone can integrate the component in their project and start using it right away (being able to easily integrate with their project through the events that are emitted by it).

The other approach would be to allow the import, within this same project, of the textarea with emoji rendering and the emoji picker separately.

It is important to remember that you can use the emoji picker only by defining these two properties to 'cooltextarea':
```javascript
enableTextarea = false
```
and
```javascript
enableSendBtn = false
```
You can also configure the emoji picker's outer div styles by passing an array of CSS class strings:
```javascript
outerDivClasses = ['new-bg-color']
```
and the emoji picker's own button:
```javascript
btnEmojiClasses = ['new-button-color']
```

The emoji picker also emits two events everytime a emoji is inserted: emojiUnicodeAdded(unicode) and emojiImgAdded(img) so you can catch and integrate the component on your app.

So let's suppose you want to use the options I told you above you could do per example:
```html
<cooltextarea
     :content.sync="content" 
     :emojiData="emojiDataAll" 
     :emojiGroups="emojiGroups"
     :enableTextarea=false
     :enableSendBtn=false
     :outerDivClasses="['new-bg-color']"
     :btnEmojiClasses="['new-button-color']"
     @enterKey="onEnterKey"
     @emojiUnicodeAdded="yourMethodToCatchInsertedEmojiUnicode"
     @emojiImgAdded="yourMethodToCatchInsertedEmojiImg"
      ref="cooltextareaRef"></cooltextarea>
```

**Comment by sololance** [comment]
@kevinfaguiar thank you for detailed reply, importing only picker would be faster than importing whole cooltextarea module, just my idea.

As I already said, if you're going to create a new project, it will be one of the best over there 🥇 

I have already tried most of the libraries ( such as https://github.com/jm-david/emoji-mart-vue ) over there and none of them works great (performance wise - 6 secs to render lol). I event tried to fix it but it needs complete rewrite to use functional programming.

**Comment by kevinfaguiar** [comment]
Regarding this issue the project now has changed its name from "CoolTextArea" to "Cool Emoji Picker". Now you can import only the emoji picker or the emoji picker  + featured textarea, at your choice.

The docs have been updated to reflect this change: https://kevinfaguiar.github.io/cool-emoji-picker/#home

The npm dependency 'cooltextarea' has been deprecated by the new one: https://www.npmjs.com/package/cool-emoji-picker
