### ISSUE TITLE
i  have  a  questions  i  can't understand  how to  use it but  my  

### ISSUE THREAD

**Issue by yanwuguangjun** [kevinfaguiar/cool-emoji-picker#5]
![image](https://user-images.githubusercontent.com/17357142/52779850-ef96d780-3083-11e9-863a-197f0fe20fff.png)

i  have  a  questions  i  can't understand  how to  use it but  my  Twemoji  was installed there is the consle's log

![image](https://user-images.githubusercontent.com/17357142/52779966-3389dc80-3084-11e9-8e0e-28732959813d.png)

**Comment by sololance** [comment]
Hi!

It should be your function in methods:
```
yourMethodToCatchEmojiUnicode: function(emoji) {
      console.log(emoji);
},

yourMethodToCatchEmojiImg: function(emoji) {
      console.log(emoji);
}
```

Also you've forgot to add `components: { 'coolpicker': CoolPicker },`

You should definitely read documentation https://kevinfaguiar.github.io/cool-emoji-picker/#home

Thanks!

**Comment by yanwuguangjun** [comment]
omg!  it's  works   thank you  so much
i'm a  green for  vue ,thanks for help
