### ISSUE TITLE
Don't work on GOOGLE CHROME (and webkit based)

### ISSUE THREAD

**Issue by shift-reality** [kevinfaguiar/cool-emoji-picker#6]
Hi! Here is code to test: `cooltextarea(:content="val",:emojiData="emojiDataAll",:emojiGroups="emojiGroups",ref="cooltextareaRef")`
`this.$refs.cooltextareaRef.addTextBlur("TEST");`
Perfect works on Firefox in Debian 9.9 Linux... Bug affects only webkit based browsers in Mac Linux and Android. (Content is NOT set to TEST, but works in firefox)
http://joxi.net/4Ak3NG7SoVlJoA http://joxi.net/KAgK1WxSEO7y7A

**Comment by shift-reality** [comment]
works if wrap into `Vue.nextTick`

**Comment by kevinfaguiar** [comment]
Can you test if this works in the latest version?

**Comment by kevinfaguiar** [comment]
Since the author did not answer I will close this issue for now... If anyone still has this bug please reopen.
