### ISSUE TITLE
Package is broken 

### ISSUE THREAD

**Issue by mishokupatadze** [kevinfaguiar/cool-emoji-picker#8]
I really liked package and would like to use it instead of existing one, but as it seems it's broken. Got error whenever installed locally, have got the same result on bundlephobia:

https://bundlephobia.com/result?p=cool-emoji-picker

**Comment by kevinfaguiar** [comment]
This package currently has no SFC (Single File Component) support. 
I will add that as an enhancement to do as soon as I can.

**Comment by kevinfaguiar** [comment]
@mishokupatadze this issue has been adressed. Now Cool Emoji Picker generates the bundles for commons, esm and UMD. Also working with bundlephobia: https://bundlephobia.com/result?p=cool-emoji-picker@4.0.0
